name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Lint
        run: npm run lint --if-present
      - name: Test and coverage
        run: npm run test:coverage
      - name: Build
        run: npm run build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@5875562561d22a34be0c657405578705a169af6c # v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
